# Generated by Django 4.0.4 on 2022-06-14 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
            ],
        ),
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '1级'), (2, '2级'), (3, '3级'), (4, '4级'), (5, '5级')], default=1, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(1, '已占用'), (2, '未占用')], default=2, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('account', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='员工工号')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('create_time', models.DateTimeField(verbose_name='入职时间')),
                ('occupation', models.SmallIntegerField(choices=[(1, '经理'), (2, '工程师'), (3, '销售员'), (4, '测试'), (5, '产品'), (6, '售后')], default=1, verbose_name='性别')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '临时')], default=3, verbose_name='级别')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详细信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.admin', verbose_name='负责人')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基本工资')),
                ('welfare_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='福利补贴')),
                ('bonus_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='奖励工资')),
                ('unemployment_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='失业保险')),
                ('housing_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='住房公积金')),
                ('salary_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实发工资')),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.userinfo', verbose_name='员工工号')),
            ],
        ),
    ]
