# Generated by Django 4.0.4 on 2022-06-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealWithLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='操作名称')),
                ('time', models.TimeField(verbose_name='操作时间')),
                ('details', models.TextField(max_length=128, verbose_name='详细信息')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='occupation',
            field=models.SmallIntegerField(choices=[(1, '经理'), (2, '工程师'), (3, '销售员'), (4, '测试'), (5, '产品'), (6, '售后')], default=1, verbose_name='职业'),
        ),
    ]
