# Generated by Django 4.0.4 on 2022-06-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_dealwithlog_alter_userinfo_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.userinfo', unique=True, verbose_name='员工工号'),
        ),
    ]
