# Generated by Django 4.0.4 on 2022-06-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_salary_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='acc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.userinfo', verbose_name='员工工号'),
        ),
    ]
