# Generated by Django 4.0.4 on 2022-06-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_salary_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartSalary',
            fields=[
                ('account', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='员工工号')),
                ('salary_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实发工资')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
            ],
            options={
                'db_table': 'departSalary',
                'managed': False,
            },
        ),
    ]
