# Generated by Django 4.0.4 on 2022-06-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_departsalary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departsalary',
            options={},
        ),
    ]
